kind: pipeline
type: docker
name: push-docker

trigger:
  branch:
    - website-rework
  event:
    - push

steps:
  - name: get-version
    image: node:slim
    commands:
      - export VERSION=$(node -p "require('./package.json').version")
      - echo $VERSION
    when:
      event:
        - push

  - name: docker
    image: plugins/docker
    settings:
      registry: registry.smashmc.eu
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: registry.smashmc.eu/nuxt-website
      tags:
        - latest
        - ${DRONE_COMMIT_BRANCH}-${DRONE_BUILD_NUMBER} # Default tag in case the version is empty
        - ${VERSION}
      dockerfile: ./Dockerfile
    depends_on:
      - get-version
    environment:
      VERSION: ${VERSION}
    when:
      event:
        - push
