kind: pipeline
type: docker
name: push-docker

trigger:
  branch:
    - website-rework
  event:
    - push

steps:
  - name: get-version
    image: node:slim
    commands:
      - export VERSION=$(node -p "require('./package.json').version")
      - echo $VERSION > .version

  - name: docker
    image: plugins/docker
    settings:
      registry:
        from_secret: registry.smashmc.eu
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: registry.smashmc.eu/nuxt-website
      tags:
        - latest
        - $(cat .version)
      dockerfile: ./Dockerfile
    depends_on:
      - get-version