kind: pipeline
type: docker
name: push-docker

trigger:
  branch:
    - website-rework
  event:
    - push

steps:
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.smashmc.eu
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: registry.smashmc.eu/nuxt-website
      tags:
        - latest
      dockerfile: ./Dockerfile