services:
  nuxt-website:
    container_name: nuxt-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NUXT_STATS_API_BASE_URL: https://example.com